name: solafune-deforestation-cpu

channels:
  - pytorch         
  - conda-forge     
  - defaults        

dependencies:
  - python=3.9
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - scikit-image
  - tifffile
  - rasterio
  - shapely
  - tqdm
  - albumentations
  - pytorch
  - torchvision
  - pytorch-lightning
  - segmentation-models-pytorch
  - timm
  - tensorboard