name: solafune-deforestation
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy=1.26.4
  - pandas
  - scikit-learn
  - matplotlib
  - scikit-image
  - tifffile
  - rasterio=1.3.6
  - shapely=2.0.1
  - tqdm
  - albumentations=1.4.24
  - imagecodecs
  - opencv
  - pytorch=2.5.1
  - torchvision=0.15.2
  - torchaudio=2.5.1
  - pytorch-lightning=2.5.0.post0
  - segmentation-models-pytorch=0.3.4
  - timm=0.9.7
  - tensorboard
  - pip
  - pip:
      - albucore==0.0.23
      - annotated-types==0.7.0
      - astunparse==1.6.3
